version: '3.7'

services:

  nginx:
    privileged: true
    image: nginx:1.23.2-alpine
    ports:
      - "80:80"
      - "${NGINX_PORT:-443}:443"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/nginx/SSL/certs/rsa:/etc/nginx/ssl
      - ./docker/api-pcs/public:/var/www/pcs/public
      - ./docker/front-pcs/development.js:/var/www/pcs/public/env.js

  postgresql:
    privileged: true
    image: "postgres:15-alpine"
    environment:
      POSTGRES_DB:       "pcs"
      POSTGRES_USER:     "pcs"
      POSTGRES_PASSWORD: "pcs"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init-db:/docker-entrypoint-initdb.d

  api-pcs:
    privileged: true
    build:
      context: ./api-pcs/
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-pcs:/usr/lib/pcs/api-pcs
      - ./docker/api-pcs/config:/usr/lib/pcs/api-pcs/config
      - ./docker/api-pcs/public:/usr/lib/pcs/api-pcs/public
    ports:
      - "3000:80"
    environment:
      NODE_ENV: development
      DATABASE_URL: 'postgresql://pcs:pcs@postgresql:5432/pcs?schema=public'
    # env_file:
    # - ./docker/nest/config/development.yaml

  api-stripe:
    privileged: true
    build:
      context: ./api-stripe/
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-stripe:/usr/lib/pcs/api-stripe
      - ./docker/api-stripe/config:/usr/lib/pcs/api-stripe/config
    ports:
      - "3002:80"
    environment:
      NODE_ENV: development

  front-pcs:
    privileged: true
    build:
      context: ./front-pcs/
      dockerfile: Dockerfile.dev
    volumes:
      - ./front-pcs:/usr/lib/pcs/front-pcs
      # - ./docker/front-pcs/development.js:/usr/lib/pcs/front-pcs/public/env.js
    ports:
      - "3003:80"
    environment:
      NODE_ENV: development
    # env_file:
    # - ./front-pcs/.env
