FROM node:18

# Create app directory
RUN mkdir -p /usr/lib/esgi/api-pcs/
WORKDIR /usr/lib/esgi/api-pcs/

# Install dependencies
COPY package.json .

RUN npm install

# Exports
EXPOSE 80
CMD [ "npm", "run", "start:dev" ]