FROM node:18-alpine

# Create app directory
RUN mkdir -p /usr/lib/esgi/front-pcs/
WORKDIR /usr/lib/esgi/front-pcs/

# # Install dependencies
COPY package.json .
RUN npm install
# RUN npm install -g react react-scripts

# Exports
EXPOSE 80
# CMD [ "npm", "run", "start-dev" ]
CMD [ "npm", "run", "start-react" ]